name: 'Test Composite Action'
description: 'Test Composite Action'
runs:
  using: "composite"
  steps:
    - run: echo Installing Java with setup-java action inside a composite action
      shell: bash
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - run: echo Done
      shell: bash
    - run: which java
      shell: bash
